//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboSMS.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TurboSMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось прочесть ответ сервера..
        /// </summary>
        internal static string CantReadServerResponse {
            get {
                return ResourceManager.GetString("CantReadServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ping.
        /// </summary>
        internal static string DefaultModuleMethod_Ping {
            get {
                return ResourceManager.GetString("DefaultModuleMethod_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан метод модуля..
        /// </summary>
        internal static string EmptyModuleName {
            get {
                return ResourceManager.GetString("EmptyModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан обязательный параметр phones.
        /// </summary>
        internal static string EmptyParam_Phones {
            get {
                return ResourceManager.GetString("EmptyParam_Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан обязательный параметр separators..
        /// </summary>
        internal static string EmptyParam_Separators {
            get {
                return ResourceManager.GetString("EmptyParam_Separators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан формат запроса..
        /// </summary>
        internal static string EmptyQueryFormat {
            get {
                return ResourceManager.GetString("EmptyQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер вернул пустой ответ..
        /// </summary>
        internal static string EmptyServerResponse {
            get {
                return ResourceManager.GetString("EmptyServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указано пустое значение..
        /// </summary>
        internal static string EmptyValue {
            get {
                return ResourceManager.GetString("EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сконвертировать данные результата в JSON формат, незамедлительно свяжитесь с нашим отделом поддержки клиентов для выяснения деталей..
        /// </summary>
        internal static string FAILED_CONVERT_RESULT2JSON {
            get {
                return ResourceManager.GetString("FAILED_CONVERT_RESULT2JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сконвертировать данные результата в XML формат, незамедлительно свяжитесь с нашим отделом поддержки клиентов для выяснения деталей..
        /// </summary>
        internal static string FAILED_CONVERT_RESULT2XML {
            get {
                return ResourceManager.GetString("FAILED_CONVERT_RESULT2XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось распознать тело запроса (неверный формат)..
        /// </summary>
        internal static string FAILED_PARSE_BODY {
            get {
                return ResourceManager.GetString("FAILED_PARSE_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить изображение..
        /// </summary>
        internal static string FAILED_SAVE_IMAGE {
            get {
                return ResourceManager.GetString("FAILED_SAVE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось отправить SMS сообщение..
        /// </summary>
        internal static string FAILED_SMS_SEND {
            get {
                return ResourceManager.GetString("FAILED_SMS_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось отправить Viber сообщение..
        /// </summary>
        internal static string FAILED_VIBER_SEND {
            get {
                return ResourceManager.GetString("FAILED_VIBER_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка выполнения запроса, свяжитесь с отделом поддержки для выяснения деталей..
        /// </summary>
        internal static string FATAL_ERROR {
            get {
                return ResourceManager.GetString("FATAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение параметра MessageId, неверный формат..
        /// </summary>
        internal static string INVALID_MESSAGE_ID {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный отправитель сообщения..
        /// </summary>
        internal static string INVALID_MESSAGE_SENDER {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение текста сообщения. Возвращается если передано не строковое значение или кодировка символов не входит в набор UTF-8..
        /// </summary>
        internal static string INVALID_MESSAGE_TEXT {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый номер получателя, система не смогла распознать страну и оператора получателя..
        /// </summary>
        internal static string INVALID_PHONE {
            get {
                return ResourceManager.GetString("INVALID_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный запрос, проверьте его структуру и корректность данных..
        /// </summary>
        internal static string INVALID_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная дата отложенной отправки сообщения..
        /// </summary>
        internal static string INVALID_START_TIME {
            get {
                return ResourceManager.GetString("INVALID_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный токен аутентификации..
        /// </summary>
        internal static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение параметра LifeTime, значение должно быть целочисленным и не представлено в виде строки..
        /// </summary>
        internal static string INVALID_TTL {
            get {
                return ResourceManager.GetString("INVALID_TTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на send.
        /// </summary>
        internal static string MessageEngineMethod_Send {
            get {
                return ResourceManager.GetString("MessageEngineMethod_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на status.
        /// </summary>
        internal static string MessageEngineMethod_Status {
            get {
                return ResourceManager.GetString("MessageEngineMethod_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на message.
        /// </summary>
        internal static string Module_Message {
            get {
                return ResourceManager.GetString("Module_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user.
        /// </summary>
        internal static string Module_User {
            get {
                return ResourceManager.GetString("Module_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст на кнопке слишком длинный, длопускается не более 30 символов..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_BUTTON_TEXT_LENGTH {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_BUTTON_TEXT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Какой-то из параметров имеет недопустимое значение, свяжитесь с нашим отделом поддержки клиентов для выяснения деталей..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_DATA {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные сообщения с переданным message_id недоступны для текущего пользователя..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_ID {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый тип файла изображения..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_IMAGE {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не разрешённый отправитель для текущего пользователя..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_SENDER {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправитель разрешён, но не активирован на данный момент (не оплачено использование в текущем месяце, не завершена регистрация и т.п.)..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_SENDER_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_SENDER_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст содержит запрещённые фрагменты..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_TEXT {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышена допустимая длина текста сообщения..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_TEXT_LENGTH {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_TEXT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый контент в транзакционном сообщении. В таких сообщениях можно отправлять только текст, а кнопка и изображения запрещены..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_TRANSACTION_CONTENT {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_TRANSACTION_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено отправлять транзакционные сообщения от общего отправителя..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_TRANSACTION_SENDER {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_TRANSACTION_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение параметра LifeTime (выходит за пределы установленных ограничений)..
        /// </summary>
        internal static string NOT_ALLOWED_MESSAGE_TTL {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_MESSAGE_TTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер получателя находится в стоплисте (для sms) или в игнорлисте (для Viber), отправка невозможна..
        /// </summary>
        internal static string NOT_ALLOWED_NUMBER_STOPLIST {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_NUMBER_STOPLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимая страна получателя. У пользователя не активирована возможность отправлять сообщения получателям данной страны. Для активации такой возможности свяжитесь с нашим отделом поддержки клиентов..
        /// </summary>
        internal static string NOT_ALLOWED_RECIPIENT_COUNTRY {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_RECIPIENT_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получатель уже присутствует в рассылке, дубликаты игнорируются..
        /// </summary>
        internal static string NOT_ALLOWED_RECIPIENT_DUPLICATE {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_RECIPIENT_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое количество получателей..
        /// </summary>
        internal static string NOT_ALLOWED_RECIPIENTS_LIMIT {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_RECIPIENTS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимая дата отложенной отправки сообщения (выходит за пределы установленных ограничений)..
        /// </summary>
        internal static string NOT_ALLOWED_START_TIME {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер не содержит ни одной цифры..
        /// </summary>
        internal static string NumberHasntDigits {
            get {
                return ResourceManager.GetString("NumberHasntDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь заблокирован, работа с API невозможна до разблокировки..
        /// </summary>
        internal static string REQUIRED_ACTIVE_USER {
            get {
                return ResourceManager.GetString("REQUIRED_ACTIVE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аутентификация не пройдена, не верный токен..
        /// </summary>
        internal static string REQUIRED_AUTH {
            get {
                return ResourceManager.GetString("REQUIRED_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не достаточно кредитов на балансе для создания рассылки..
        /// </summary>
        internal static string REQUIRED_BALANCE {
            get {
                return ResourceManager.GetString("REQUIRED_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствуют данные запроса..
        /// </summary>
        internal static string REQUIRED_CONTENT {
            get {
                return ResourceManager.GetString("REQUIRED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствуют или пустые параметры кнопки в сообщении, когда она обязательна..
        /// </summary>
        internal static string REQUIRED_MESSAGE_BUTTON {
            get {
                return ResourceManager.GetString("REQUIRED_MESSAGE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует или пустой параметр URL адреса, куда перейдёт получатель сообщения при нажатии на кнопку..
        /// </summary>
        internal static string REQUIRED_MESSAGE_BUTTON_ACTION {
            get {
                return ResourceManager.GetString("REQUIRED_MESSAGE_BUTTON_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует или пустой параметр текста на кнопке в сообщении..
        /// </summary>
        internal static string REQUIRED_MESSAGE_BUTTON_CAPTION {
            get {
                return ResourceManager.GetString("REQUIRED_MESSAGE_BUTTON_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует или пустой список получателей сообщения..
        /// </summary>
        internal static string REQUIRED_MESSAGE_RECIPIENT {
            get {
                return ResourceManager.GetString("REQUIRED_MESSAGE_RECIPIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует или пустой параметр отправителя сообщения..
        /// </summary>
        internal static string REQUIRED_MESSAGE_SENDER {
            get {
                return ResourceManager.GetString("REQUIRED_MESSAGE_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует или пустой параметр текста сообщения..
        /// </summary>
        internal static string REQUIRED_MESSAGE_TEXT {
            get {
                return ResourceManager.GetString("REQUIRED_MESSAGE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует токен аутентификации..
        /// </summary>
        internal static string REQUIRED_TOKEN {
            get {
                return ResourceManager.GetString("REQUIRED_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщения успешно созданы и добавлены в очередь отправки. Некоторые сообщения могут попадать на предварительную модерацию..
        /// </summary>
        internal static string SUCCESS_MESSAGE_ACCEPTED {
            get {
                return ResourceManager.GetString("SUCCESS_MESSAGE_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщения успешно созданы и добавлены в очередь отправки, но некоторые получатели не попали в список рассылки, детали смотрите в ответе..
        /// </summary>
        internal static string SUCCESS_MESSAGE_PARTIAL_ACCEPTED {
            get {
                return ResourceManager.GetString("SUCCESS_MESSAGE_PARTIAL_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщения успешно отправлены, но некоторые получатели не попали в список рассылки, детали смотрите в ответе..
        /// </summary>
        internal static string SUCCESS_MESSAGE_PARTIAL_SENT {
            get {
                return ResourceManager.GetString("SUCCESS_MESSAGE_PARTIAL_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщения успешно отправлены..
        /// </summary>
        internal static string SUCCESS_MESSAGE_SENT {
            get {
                return ResourceManager.GetString("SUCCESS_MESSAGE_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля ResponseStatus непредусмотренно.
        /// </summary>
        internal static string UNKNOWN_VALUE {
            get {
                return ResourceManager.GetString("UNKNOWN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на balance.
        /// </summary>
        internal static string UserEngineMethod_Balance {
            get {
                return ResourceManager.GetString("UserEngineMethod_Balance", resourceCulture);
            }
        }
    }
}
